/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

// Study guide for this project - https://drive.google.com/file/d/1s5grutGuQFwJcQP8bFwEI69Q8FCkGdDk/view?usp=sharing

//create quotes array
var quotes = [
    {
        quote: 'No man ever steps in the same river twice, for its not the same river and he is not the same man',
        source: 'Heraclitus',
        citation: 'Ephesus',
        year: 'C.500 BC',
        tags: ['Philosophy', 'Greek']
    },
    {
        quote: 'Suffering exists',
        source: 'Siddhartha Gautama',
        citation: 'India',
        year: 'C.500 BC',
        tags: ['Philosophy', 'Indian']
    },
    {
        quote: 'The die is cast',
        source: 'Julius Caesar',
        citation: 'Northern Italy',
        year: '49 BC',
        tags: ['Direct Quote', 'Roman']
    },
    {
        quote: 'The only true wisdom is knowing you know nothing',
        source: 'Socrates',
        citation: 'Greece',
        year: '469 BC - 399 BC',
        tags: ['Philosophy', 'Greek']
    },
    {
        quote: 'We are what we repeatedly do; excellence then is not an act but a habit',
        source: 'Aristotle',
        citation: 'Greece',
        year: '384 BC - 322 BC',
        tags: ['Philosophy', 'Greek']
    },
    {
        quote: 'He has half the deed done who has made a beginning',
        source: 'Horace',
        citation: 'Rome',
        year: '65 BC - 8 BC',
        tags: ['Philosophy',  'Roman']
    },
    {
        quote: 'The nature of man is always the same; it is their habits that separate them',
        source: 'Confucius',
        citation: 'China',
        year: '551 BC - 479 BC',
        tags: ['Philosophy', 'Chinese']
    },
    {
        quote: 'There is nothing permanent except change',
        source: 'Heraclitus',
        citation: 'Greece',
        year: '4th Century BC',
        tags: ['Philosophy', 'Greek']
    },
    {
        quote: 'The real destroyer of the liberties of the people is he who spreads among them bounties, donations and benefits',
        source: 'Plutarch',
        citation: 'Greece',
        year: '1st Century BC',
        tags: ['Philosophy', 'Greek']
    },
    {
        quote: 'At his best, man is the noblest of all animals; separated from law and justice he is the worst',
        source: 'Heraclitus',
        citation: 'Greece',
        year: '4th Century BC',
        tags: ['Philosophy', 'Greek']
    }
];

console.log(quotes);

//create random number matching number of objects in array, grab the element stored in this index in array and return object.
function getRandomQuote() {
    let randomNum = Math.floor(Math.random() * quotes.length);
    let quoteObject = quotes[randomNum];
    return quoteObject;
}


//function to generate random css colour
function randomColour(){
    let generatedHex = Math.floor(Math.random()*16777215).toString(16);
    return generatedHex;
}

    //Function to add new quotes on timer and with user action as per listener.
    function printQuote() {

        let currentQuote = getRandomQuote();
        let insertQuoteHTML = "";

            /*** Insert object info based on HTML structure from index.html
            *** Check if additional fields are populated, adding into HTML if they have a value
            *** Replace HTML in document with the content generated by the function.
            *** Change bg colour using randomColour function and line of code to change styling
            **/

        insertQuoteHTML += "<p class=\"quote\">" + currentQuote.quote +  "</p>";
        insertQuoteHTML += "<p class=\"source\">" + currentQuote.source + "</span>";

        if (currentQuote.citation != "") {
            insertQuoteHTML += "<span class=\"citation\">" + currentQuote.citation + "</span>"
            }

        if (currentQuote.year != "") {
            insertQuoteHTML += "<span class=\"year\">" + currentQuote.year + "</span>";
        }

        if (currentQuote.tags[0] != "") {
            insertQuoteHTML += "<p class=\"tags\">" + currentQuote.tags.join(', ') + "</p>"
        }

        insertQuoteHTML += "</p>";

        document.getElementById("quote-box").innerHTML = insertQuoteHTML;

        /** Call random colour function and generate hex string for entry into background colour styling
        *** Duplicate this colour in the show another quote box
        **/
        let newColour = '#' + randomColour();
        document.body.style.backgroundColor = newColour;
        document.getElementById("loadQuote").style.backgroundColor = newColour;
    }

//Trigger printQuote method to trigger every 10 seconds
let switchTime = setInterval(printQuote, 10000);


//listener code below:
document.getElementById('loadQuote').addEventListener("click", printQuote, false);

